Removed support for outdated kubernetes releases.
gardener/gardener-extension-networking-calico pull request #150
Opened 2022-02-08 10:56 UTC by ScheererJ

Now, kubernetes 1.17 and above is required as the minimum.

**How to categorize this PR?**

/area networking
/kind cleanup

**What this PR does / why we need it**:
Removed support for outdated kubernetes releases.
Now, kubernetes 1.17 and above is required as the minimum.

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:

**Release note**:

```other operator
Kubernetes releases older than 1.17 are no longer supported by the gardener calico extension.
```

2022-02-08 11:06 UTC, DockToFuture requested changes
/lgtm, there are also two more blocks (">= 1.17") in:
- `gardener-extension-networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-ipreservations.yaml` 
- `gardener-extension-networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-caliconodestatuses.yaml`
which can be removed. I think its sufficient to keep that information in the targetVersion.

2022-02-09 07:50 UTC, ScheererJ commented
> /lgtm, there are also two more blocks (">= 1.17") in:
> 
> * `gardener-extension-networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-ipreservations.yaml`
> * `gardener-extension-networking-calico/charts/internal/calico/templates/custom-resource-definition/crd-caliconodestatuses.yaml`
>   which can be removed. I think its sufficient to keep that information in the targetVersion.

Removed version checks in those two files as well.

2022-02-09 07:57 UTC, DockToFuture approved these changes
/lgtm

2022-02-14 07:02 UTC, rfranzke approved these changes

2022-02-14 08:23 UTC, merged