Add node.gardener.cloud/critical-component to calico-node DaemonSet
gardener/gardener-extension-networking-calico pull request #236
Opened 2023-02-02 14:11 UTC by dergeberl

**How to categorize this PR?**

/area robustness
/kind enhancement

**What this PR does / why we need it**:

This PR adds the `node.gardener.cloud/critical-component` introduced in https://github.com/gardener/gardener/pull/7406 

**Which issue(s) this PR fixes**:
Part of  https://github.com/gardener/gardener/issues/7117

**Special notes for your reviewer**:

**Release note**:

```other operator
Add node.gardener.cloud/critical-component to calico-node DaemonSet
```

2023-02-10 07:51 UTC, timebertt requested changes

2023-02-10 07:51 UTC, timebertt commented on charts/internal/calico/templates/node/daemonset-calico-node.yaml
> +        node.gardener.cloud/critical-component: "true"
The label needs to be added to the `DaemonSet` metadata as well now, see https://github.com/gardener/gardener/issues/7117#issuecomment-1425346730.

2023-02-15 09:37 UTC, timebertt commented
/unhold
now that https://github.com/gardener/gardener/pull/7406 is merged

2023-02-17 06:52 UTC, timebertt approved these changes
/lgtm

2023-02-20 09:57 UTC, DockToFuture approved these changes
/lgtm

2023-02-20 09:57 UTC, merged