switch GCR -> Artifact-Registry
gardener/gardener-extension-networking-calico pull request #321
Opened 2023-11-30 19:20 UTC by ccwienk

GCR has been deprecated [0] in favour of Artifact-Registry.

Thus, change push-targets for OCI-Images:

- europe-docker.pkg.dev/gardener-project/snapshots for snapshots
- europe-docker.pkg.dev/gardener-project/releases for releases

To allow users for smooth transitioning, keep also publishing to GCR.

[0]
https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr

**Release note**:

```breaking operator
Change OCI Image Registry from GCR (`eu.gcr.io/gardener-project`) to Artifact-Registry (`europe-docker.pkg.dev/gardener-project/releases`). Users should update their references.

```

2023-11-30 20:05 UTC, ccwienk commented
/test pull-extension-networking-calico-e2e-kind

2023-11-30 20:44 UTC, ccwienk commented
/test pull-extension-networking-calico-e2e-kind

2023-12-01 10:11 UTC, ScheererJ commented on hack/test-e2e-provider-local.sh
> +docker tag europe-docker.pkg.dev/gardener-project/snapshots/extensions/networking-calico:latest networking-calico-local:$version
Will this work for release build? If we push them to a different path how should this work?

2023-12-04 17:20 UTC, ccwienk commented
/test pull-extension-networking-calico-e2e-kind

2023-12-04 20:12 UTC, ccwienk commented
/test pull-extension-networking-calico-e2e-kind

2023-12-04 20:26 UTC, ccwienk commented
/test pull-extension-networking-calico-e2e-kind

2023-12-04 20:28 UTC, ccwienk commented
/test pull-extension-networking-calico-e2e-kind

2023-12-05 11:37 UTC, DockToFuture approved these changes
/lgtm

2023-12-05 11:59 UTC, ScheererJ requested changes
@ccwienk Please apply the same changes as in the cilium extension also here.

2023-12-05 17:07 UTC, ccwienk commented
I think/hope to have addressed all review feedback (thanks for your thorough review!). This pull-request should now also be in sync w/ the one for [cilium](https://github.com/gardener/gardener-extension-networking-cilium/pull/231)

2023-12-06 08:02 UTC, ScheererJ approved these changes
Thanks for the changes.

/lgtm

2023-12-06 08:04 UTC, merged