Determine iptables backend in container add-snat-rule-to-upstream-dns.
gardener/gardener-extension-networking-calico pull request #324
Opened 2023-12-06 15:42 UTC by axel7born

The calico-node container determines the backend of iptables in the calico-node executable based on existing chains in the mangle table. The container `add-snat-rule-to-upstream-dns` adds additional rules to masquerade traffic to the upstream DNS server. These rules must added with the same iptables version as used by calico-node. For that reason this PR adds a iptables-backend detection to this container.

In addition to that, we mount the xtables lock file into `add-snat-rule-to-upstream-dns`. 

**How to categorize this PR?**

/area networking
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Determine iptables backend in container add-snat-rule-to-upstream-dns.
```

2023-12-06 15:52 UTC, DockToFuture commented on charts/internal/calico/templates/node/daemonset-calico-node.yaml
> +            if [[ $nft_kubelet_rules != "" ]]; then
```suggestion
            if [[ -n $nft_kubelet_rules ]]; then
```

2023-12-06 16:01 UTC, ScheererJ requested changes
Thanks for adding proper nft/legacy support.

2023-12-06 16:01 UTC, ScheererJ commented on charts/internal/calico/templates/node/daemonset-calico-node.yaml
> +              readOnly: false
Nit: Usually the `volumeMounts` are at the end of the container specification. Not really a problem, but I was just a bit surprised.

2023-12-07 07:42 UTC, DockToFuture approved these changes
/lgtm :)

2023-12-07 08:32 UTC, ScheererJ approved these changes
/lgtm

2023-12-07 08:33 UTC, merged