Update pull_request_template.md
gardener/gardener-extension-networking-calico pull request #61
Opened 2020-11-10 12:22 UTC by DockToFuture

Remove duplicated entry

**How to categorize this PR?**

/area TODO
/kind TODO
/priority normal
/area networking

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2020-11-10 12:41 UTC, rfranzke requested changes
You have to adapt https://github.com/gardener/gardener-extension-networking-calico/blob/master/hack/update-github-templates.sh

2020-11-13 08:25 UTC, DockToFuture commented
Can we merge this?

2020-11-13 08:44 UTC, timebertt approved these changes

2020-11-13 09:05 UTC, rfranzke approved these changes
/lgtm

2020-11-13 09:05 UTC, merged