landscaper integration
gardener/gardener-extension-networking-calico pull request #83
Opened 2021-05-18 08:02 UTC by jschicktanz

**How to categorize this PR?**

/area delivery
/kind enhancement

**What this PR does / why we need it**:
adds artifacts for Landscaper integration (blueprint, resources definition file, component descriptor build script)

co-authored by @enrico-kaack-comp 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
- adds artifacts for Landscaper integration
```

2021-05-18 08:02 UTC, jschicktanz commented
/invite @schrodit

2021-05-18 08:12 UTC, ScheererJ submitted a review, later dismissed
/lgtm

2021-05-18 09:10 UTC, DockToFuture approved these changes
/lgtm

2021-05-26 13:57 UTC, rfranzke commented on .landscaper/blueprint/deploy-executions.yaml
> +              {{- end }}
Please use `ControllerDeployment`s instead, see https://github.com/gardener/gardener/pull/3995

2021-05-27 06:56 UTC, schrodit requested changes

2021-05-27 06:56 UTC, schrodit commented on .landscaper/resources.yaml
> +  compress: true
I think we need also `preserveDir` for helm to properly work

2021-06-01 08:18 UTC, rfranzke commented
/author-action

2021-06-11 06:31 UTC, rfranzke commented
/assign @schrodit

2021-06-11 07:57 UTC, schrodit requested changes
please update the media type otherwise lgtm

2021-06-11 07:57 UTC, schrodit commented on .landscaper/resources.yaml
> +    mediaType: "application/vnd.gardener.landscaper.blueprint.v1+tar+gzip"
```suggestion
    mediaType: "application/vnd.gardener.landscaper.blueprint.layer.v1.tar+gzip"
```

2021-06-11 12:54 UTC, rfranzke approved these changes

2021-06-11 13:04 UTC, merged